version: '3.8'

services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000" 
    env_file:
      - .env  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
